version : "3"

services: 
  db:   
    image: postgres
    environment:  
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "test"
      POSTGRES_DB: "test"
    ports: 
      - 5432:5432
    volumes: 
      - db_data:/var/lib/postgresql/data

volumes:    
  db_data:

